### ISSUE TITLE
style folders sidebar 

### ISSUE THREAD

**Issue by bigdiff** [nathanielevan/gruvbox-material-telegram#2]
on telegram desktop currently the folders sidebar is not colored with gruvbox.
to enable folders on telegram desktop:

1. go to settings
2. folders
3. create new folder
4. choose name and chat then click create
5. exit settings

now the folders sidebar should appear

**Comment by nathanielevan** [comment]
Hi, thanks for the report -- please check if the issue has been fixed, if it hasn't, feel free to re-open the issue. Thank you!

**Comment by bigdiff** [comment]
fixed :tada: :rocket: :100: thanks
